name: 'Upload artifact with retries'
description: 'This action makes a few attempts to upload an artifact'
inputs:
  name:
    required: true
    type: string
  path:
    required: true
    type: string
runs:
  using: "composite"
  steps:
    - name: Tar # this step is important to preserve artifact permissions, without tar'ing they are lost
      id: tar
      run: |
        shopt -s globstar
        tar -cvf artifact.tar --ignore-failed-read ${{ inputs.path }}
        ls -la artifact.tar
      shell: bash
    - name: Upload - 1st attempt
      id: upload1
      uses: cytopia/upload-artifact-verify-action@v0.1.12
      with:
        name: ${{ inputs.name }}
        path: artifact.tar
      continue-on-error: true
    - name: Upload build artifacts 2nd attempt
      id: upload2
      if: steps.upload1.outcome == 'failure'
      uses: cytopia/upload-artifact-verify-action@v0.1.12
      with:
        name: ${{ inputs.name }}
        path: artifact.tar
      continue-on-error: true
    - name: Upload build artifacts 3rd attempt
      id: upload3
      if: steps.upload2.outcome == 'failure'
      uses: cytopia/upload-artifact-verify-action@v0.1.12
      with:
        name: ${{ inputs.name }}
        path: artifact.tar
      continue-on-error: true
    - name: Check if any upload was successful
      if: success() || failure()
      run: |
        if [ "${{ steps.upload1.outcome }}" == "success" ] || [ "${{ steps.upload2.outcome }}" == "success" ] || [ "${{ steps.upload3.outcome }}" == "success" ]; then
          echo "Upload was successful"
        else
          echo "All upload attempts failed"
          exit 1
        fi
      shell: bash
